FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.7.1 \
    POETRY_VIRTUALENVS_CREATE=false

RUN pip install --no-cache-dir "poetry==${POETRY_VERSION}"

WORKDIR /app

# Instalar deps de test (dev)
COPY pyproject.toml poetry.lock* ./
RUN poetry install --with dev --no-interaction --no-ansi

# Copiar el código y tests
COPY . .

CMD ["pytest", "-q"]
