version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]

volumes:
  mongo_data:
