services:
  app:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  mongo-test:
    image: mongo:6
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["poetry", "run", "test"]
    env_file:
      - .env.test
    depends_on:
      mongo-test:
        condition: service_healthy

volumes:
  mongo_data: