[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# E/F/W = pycodestyle/pyflakes, I = isort, B = flake8-bugbear, C4 = flake8-comprehensions, UP = pyupgrade, S = bandit
select = ["E", "F", "W", "I", "B", "C4", "UP", "S"]
ignore = []

[tool.ruff.lint.per-file-ignores]
# S101: Allow 'assert' in test files, as it's the standard for pytest.
"tests/**/*.py" = ["S101"]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
plugins = ["pydantic.mypy"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
asyncio_mode = "auto"
